# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import robster_pb2 as protos_dot_robster__pb2


class RobsterStub(object):
    """define service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAnalysis = channel.unary_unary(
                '/robster.Robster/ExecuteAnalysis',
                request_serializer=protos_dot_robster__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=protos_dot_robster__pb2.AnalysisResponse.FromString,
                )


class RobsterServicer(object):
    """define service
    """

    def ExecuteAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobsterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAnalysis,
                    request_deserializer=protos_dot_robster__pb2.AnalysisRequest.FromString,
                    response_serializer=protos_dot_robster__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robster.Robster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Robster(object):
    """define service
    """

    @staticmethod
    def ExecuteAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/robster.Robster/ExecuteAnalysis',
            protos_dot_robster__pb2.AnalysisRequest.SerializeToString,
            protos_dot_robster__pb2.AnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
